### ISSUE TITLE
Take the Router Challenge

### ISSUE THREAD

**Issue by grahammendick** [alshdavid/crayon#1]
It's not healthy for the Router market to be so dominated by the React Router. I want to level the playing field so that your Crayon router gets a fair crack of the whip. That's why I've written the [Router Challenge](https://github.com/grahammendick/router-challenge). It aims to do for Routers what TodoMVC did for UI frameworks by offering the same SPA built in React using different Routers. For it to be successful I need your help. Will you [take the Router Challenge](https://github.com/grahammendick/router-challenge/blob/master/CONTRIBUTING.md) and implement the SPA using your Crayon router, please?

**Comment by alshdavid** [comment]
Hi, thank you for posting this challenge!

I'm hoping to have enough time to commit to it in the future, but for now here is a similar application to the one in your test!

https://github.com/alshdavid/crayon/tree/master/examples/crayon-react-app

There's also a gif of it on the readme of the github repo.

I'm going to close this issue for now and hopefully when I get some time, I'll reopen it and we'll see what the router is capable of!
