### ISSUE TITLE
Crayon with Svelte 3

### ISSUE THREAD

**Issue by ansarizafar** [alshdavid/crayon#11]
I am defining the route like this
````
app.router.path('/', (req, res) => res.mount(() => res.mount(Test, { ...app, ...req })))
````

but I am getting this error
````
Uncaught (in promise) TypeError: Component is not a constructor
    at mounter.js:44
    at SvelteMounter.<anonymous> (mounter.js:23)
    at Generator.next (<anonymous>)
    at mounter.js:7
    at new Promise (<anonymous>)
    at __awaiter (mounter.js:3)
    at SvelteMounter.push (mounter.js:19)
    at mount.js:20
    at Generator.next (<anonymous>)
    at mount.js:7
livereload.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
````

**Comment by alshdavid** [comment]
Hey thanks for raising the issue,

What version of Crayon are you using? 
Are you using the example svelte app as a base or are you starting from scratch?

If possible could you send through a zip of your codebase?

**Comment by alshdavid** [comment]
Also you might run into trouble spreading your dependencies into your component's props

```typescript
res.mount(Test, { ...app, ...req }))
```

Means your component needs to have internal mappings for the properties of the respective objects.

Where if you pass just the object, you can access them with their names

```typescript
res.mount(Test, { app, req }))
```

```html
<script>
	export let req
	export let app
</script>
```

**Comment by alshdavid** [comment]
Perhaps compare your codebase to the following:

[svelte-example.zip](https://github.com/alshdavid/crayon/files/3189436/svelte-example.zip)

**Comment by alshdavid** [comment]
Closing this issue as I'm pretty sure the solution posted above will solve your issue :)

Feel free to reopen if not
