### ISSUE TITLE
Any way that you could handle reload

### ISSUE THREAD

**Issue by razvn** [alshdavid/crayon#2]
Hi,

Nice project that arrives right on time when I started playing seriously with Svelte. 
Works greate, beside this little problem. When I hit reload (or the server reload the site because of sources changes) it gives a 404... 

I guess that's not easy without a express like server running, but in that case couln't you support a # route instead of / ?

Thanks again,

**Comment by razvn** [comment]
Or add to description the informations like pagejs gives:
https://github.com/visionmedia/page.js#server-configuration

**Comment by alshdavid** [comment]
Excellent suggestion. Svelte is a little different as I'm not too familiar with roll-up and haven't been able to get the server to play nice with SPAs.

I'll close this issue after I've writen some documentation, and maybe supplied a starter project.

In the meantime I have updated this project:

https://github.com/alshdavid/crayon/tree/master/examples/svelte

You'll need 2 terminals. One running `npm run autobuild` and the other running `npm run serve`

You'll have to manually reload, but it works with SPAs

**Comment by alshdavid** [comment]
Ok updated both:

https://github.com/alshdavid/crayon/tree/master/examples/svelte-animated
https://github.com/alshdavid/crayon/tree/master/examples/svelte

To support SPA mode.

To get going, just run

```
npm install
npm start
```
