### ISSUE TITLE
TypeError: app.history.currentEvent is undefined

### ISSUE THREAD

**Issue by aigr** [alshdavid/crayon#26]
**Description**
When trying to use the demo I only get the error `TypeError: app.history.currentEvent is undefined` in the console.

**To Reproduce**
1. `git clone https://github.com/alshdavid/crayon.git`
2. `cd crayon/examples/svelte-animated/`
3. `npm install`
4. `npm run dev`
5. Point your browser to the server.

**Expected behavior**
A demo of how to use Crayon with Svelte and animations...

**Desktop**
 - OS: Debian GNU/Linux 9.9 (stretch)
 - Crayon: latest

**Comment by aigr** [comment]
Still can't get this to work :(

**Comment by alshdavid** [comment]
Just pushed an update to the animation middle-ware. Seems to be fixed from version 1.1.1 of crayon-animate.

Please let me know if you have any more troubles and I'll re-open this issue

**Comment by aigr** [comment]
:+1:
