### ISSUE TITLE
Crayon-Svelte Component Intro

### ISSUE THREAD

**Issue by sandman18** [alshdavid/crayon#28]
Hello,

I was curious if it is possible to add the intro:true to the client-side app when mounting?  I have a transition that plays on the initial load.  

Thanks!

**Comment by alshdavid** [comment]
Thanks for the suggestion, will spend some time implementing this!

**Comment by alshdavid** [comment]
The router currently adds a `.name-enter-first` class upon first entry. Would targeting your styles on that class name allow you to use your animation?

**Comment by alshdavid** [comment]
Closing this for now, if this is still an issue please reopen this ticket
