### ISSUE TITLE
Svelte nested routing example

### ISSUE THREAD

**Issue by artecoop** [alshdavid/crayon#30]
I'd love to see a clear example of how to make a nested routing in svelte (or framework agnostic) to better comprehend how it works.
Readme points out how to do it, but marginally and without a real example.
Please 🙏🙏🙏

**Comment by alshdavid** [comment]
Sure thing! Am working on a large project using the router so will be some delay before I get around to doing it in Svelte. Here is an example of a react implementation:

It's using the hooks API to abstract the creation of the router, but essentially all you need to do is 

- Grab an element reference to project a nested router inside
- Create a new router and project it into the reference
- Set the parent router to not redraw between those router by using `/page/**`
- Set the nested router to be in charge of `/page/a` `/page/b`

https://stackblitz.com/edit/react-9rbwas

**Comment by artecoop** [comment]
Yoo!
stackblitz does not support svelte 3 right now. I uploaded a repo here on github
https://github.com/artecoop/svelte-crayon

But it does not render nested router. In fact it clears the whole page like there is an error, but no console or other error during compilation

**Comment by alshdavid** [comment]
Hmm, Svelte could be rerendering the page unexpectedly, deleting the nested router.
You might need to use sveltes natural element reference obtaining capabilities to achieve this
```
bind:this={myElement}
```
https://svelte.dev/docs#bind_element

**Comment by alshdavid** [comment]
Hey spent some time messing with your example and I have it working. Check it out here:
https://d3c3lbb2wp865u.cloudfront.net/random/svelte-crayon-master 2.zip

Though, in doing so I found there is a bug in the mounting for svelte allowing it to only go one level deep. Thanks for getting me to look into this. I'll address the bug in the [upcoming release.](https://github.com/alshdavid/crayon/tree/release/4.0.0)

**Comment by artecoop** [comment]
Hey @alshdavid, I'll try it today. Thanks for your support!

**Comment by alshdavid** [comment]
No worries, thank you for using my project!
