### ISSUE TITLE
Route parameter converted to lowercase

### ISSUE THREAD

**Issue by srobertson421** [alshdavid/crayon#39]
**Describe the bug**
When programmatically routing using router.navigate, parameters are converted to lowercase. Could be due to URL encoding methods.

This code:
```
const id = 'WVPvZIHkGdoi1UlSsSdF';
nav.navigate(`/deal/${id}`);
```

produces this URL: `/deal/wvpvzihkgdoi1ulsssdf`

this is the route code:

```
app.path('/deal/:id', async (req, res) => {
      if(!$user && req.routePattern !== '/auth') {
        res.redirect('/auth');
      } else {
        const Deal = await import('./views/Deal.svelte');
        res.mount(Deal.default, { req, nav: app });
      }
    });
```

**To Reproduce**
1. Create route with param
2. Create button to navigate to route with param that has upper case letters
3. Click button
4. Check URL for lowercased param

**Expected behavior**
Expect route param to not be changed

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Version of Crayon: 4.1.3
 - Version of Crayon-Svelte: 1.0.10

**Additional context**
Was solved at one point by this PR: https://github.com/alshdavid/crayon/pull/31

**Comment by srobertson421** [comment]
Looks like this is the culprit: https://github.com/alshdavid/crayon/blob/master/src/router/src/platform/history/history.ts#L69

Should be:

```
path = url.normalise(path, false);
```

I can open a PR

**Comment by srobertson421** [comment]
#40 PR here

**Comment by alshdavid** [comment]
Merged

**Comment by alshdavid** [comment]
https://github.com/alshdavid/crayon/pull/41
