### ISSUE TITLE
Not a function: res.redirect , res.mount

### ISSUE THREAD

**Issue by Manuelbaun** [alshdavid/crayon#54]
Hi, I am looking for clientside routing and found crayon.

**Describe the bug**
I just cloned the Repo for Svelte and run npm install  for the basic example.
For some reason, it says in the console **res.redirect**, or **res.mount** is not a function

![image](https://user-images.githubusercontent.com/8715085/74082007-b7876200-4a55-11ea-8f91-6ef4ef1d9cd5.png)

When npm install, it would install the latest version of both, crayon and crayon svelte.

When I try to use the examples provided in codesandbox here:
* [Example 1](https://codesandbox.io/s/weathered-cdn-goup2)
* [Example 2](https://codesandbox.io/s/old-river-6l852)
it works.  It uses a different version of this library. 

```
  "dependencies": {
    "crayon": "3.0.5",
    "crayon-svelte": "1.0.5",
    "rxjs": "6.5.2",
    "svelte": "^3.0.0"
  },
```

When installing the provided example from this repo it will install:

```
crayon@6.0.1,
crayon-svelte@6.0.0
```

so my guess is, something broke.

**Comment by alshdavid** [comment]
I may not have updated the documentation but I have unified res and req. `ctx.redirect` should work

**Comment by Manuelbaun** [comment]
thank you, it did solve my issue.

**Comment by alshdavid** [comment]
I have updated the documentation
