### ISSUE TITLE
wrong svelte logo

### ISSUE THREAD

**Issue by johnmuhl** [alshdavid/crayon#59]
**Describe the bug**
The readme uses the logo from https://www.svelteproducts.com/ which is 100% unrelated to [svelte the framework](https://svelte.dev/)

**To Reproduce**
1. Open readme

**Expected behavior**
Use the official project logo; e.g.
https://svelte.dev/svelte-logo-horizontal.svg

**Comment by alshdavid** [comment]
Thanks for the heads up. Updated
